### ISSUE TITLE
checklist to launch bsv 2.0

### ISSUE THREAD

**Issue by ryanxcharles** [moneybutton/bsv#148]
The bsv 2.0 branch is here: https://github.com/moneybutton/bsv/tree/bsv2

* [x] use modern javascript
* [x] be easy to understand by using simple conventions and internal consistency
* [x] quadratic signing speed improvement
* [x] be able to use multiple versions of library, such as inside dependencies, and stop getting that 'multiple version of bsv' error
* [x] support tree-shaking so that parts of the library can be included separately. the proper way to do this is that you ought to be able to use modern `import` syntax on 'bsv' directly, and for each part of the library to accessible in a tree-shakable way that way, e.g. `import Address from 'bsv'`.
* [x] make sure bsv 1.x is still accessible and maintainable for people who can't migrate quickly. see bsv-legacy branch: https://github.com/moneybutton/bsv/tree/bsv-legacy
* [ ] have documentation that is at least as good as bsv 1.x
* [ ] check types for all common methods
* [x] remove support for p2sh in addresses and tx-builder
* [x] remove BIP 68 / relative lock time / CHECKSEQUENCEVERIFY
* [ ] update script interpreter to match genesis
* [x] default to modern flags for tx verifier to make signing/verification easier for developers <del>remove all obsolete flags for transaction signing and the script interpreter, support only the most common case of SIGHASH_FORKID, and make them easier to use for developers (legacy SIGHASH stuff only needs to be understood by nodes, not modern wallets)</del>
* [ ] support spanish and chinese for bip 39 without increasing file size
* [x] publish minified build so you can easily include the entire library monolithically in a web browser (although discouraged for production - use a custom build with tree shaking)
* [ ] match features of electrum ecies inside bsv 1
* [x] remove the injecter - thank you @ty-everett !
* [x] remove "copay" address type
* [x] use simplified ec library without extra curves: https://github.com/moneybutton/bitcoin-elliptic
* [ ] document benchmarks
* [ ] restore workers
* [x] remove BSV_USE_LIB_SECP256K1
* [ ] add regtest constants
* [ ] add typescript file
* [ ] use inside Money Button (and is therefore production-ready)

**Comment by ty-everett** [comment]
Since Groc is not currently maintained, I started a branch that uses [DocumentationJS](https://github.com/documentationjs/documentation) to generate a documentation website for the project. Documentation can be generated with the `yarn doc` command. A simple Netlify deployment could be used to build and host the documentation. You can find the branch [here](https://github.com/ty-everett/bsv/tree/feature/good-documentation). I hope this can be the first step towards having better documentation than 1.x. I will raise the PR and respond to any feedback, then we can start the process of going through the codebase and adding JSDoc where necessary.

**Comment by ryanxcharles** [comment]
closed by https://github.com/moneybutton/bsv/commit/dafea4a1c0d555d9d97408965cf3d1c564e8edc7
