### ISSUE TITLE
bsv 2.1 epic checklist

### ISSUE THREAD

**Issue by ryanxcharles** [moneybutton/bsv#184]
* [ ] have documentation that is at least as good as bsv 1.x
* [ ] check types for all common methods
* [ ] update script interpreter to match genesis
* [ ] support spanish and chinese for bip 39 without increasing file size
* [ ] match features of electrum ecies inside bsv 1
* [ ] document benchmarks
* [ ] restore workers
* [ ] add regtest constants
* [ ] add typescript file

**Comment by freddiehonohan** [comment]
Great library, thank you for this work 👍 
Regarding the final item:
> make it so that in TESTNET/MAINNET mode when you generate a new object, it gives you what you expect
This is a shared objective, how do you envision this implemented?

I see there are unused files:
```testnet-address.js
testnet-bip-32.js
testnet-key-pair.js
testnet-priv-key.js
mainnet-address.js
mainnet-bip-32.js
mainnet-key-pair.js
mainnet-priv-key.js 
```
Is this a start? What about a wallet class with mode conditional retrieval functions?
Thanks
